name: Upload to Geode Index

on:
  workflow_dispatch:

jobs:
  upload:
    permissions:
      actions: read
      contents: write

    name: Upload to Geode Index
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dawidd6/action-download-artifact@v7
        with:
          workflow: multi-platform.yml
          name: Build Output
          path: ./BuildOutput

      - name: Set Up Values
        run: |
          echo "MOD_VERSION=$(cat mod.json | jq -r .version)" >> $GITHUB_ENV
          echo "CHANGELOG=$(awk 'BEGIN { in_section = 0 } ; /^#.+/ { if (in_section) exit; next } ; /./ { in_section = 1; print }' changelog.md || echo Automatic update to $MOD_VERSION)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: BuildOutput/*
          body: ${{ env.CHANGELOG }}
          tag_name: ${{ env.MOD_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: echo ${{ fromJSON(steps.create_release.outputs.assets) }} 
